apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentview
  labels:
    app: rentview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentview
  template:
    metadata:
      labels:
        app: rentview
    spec:
      containers:
        - name: rentview
          image: username/rentview:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5